- .travis.yml
- _build.sh
- generate.py
- run_tests.sh
- templates/_c.cpp.tmpl
- templates/py.tmpl
> Enable travis-ci on linux

- .travis.yml
- run_tests.sh
- templates/py.tmpl
- tests/test_shape_python_bindings.py
> replace map by an explicit loop for python3

- .travis.yml
- Dockerfile
- README.md
Testing if this travis.yml is good - works locally
> Containerise tests - WIP

- .travis.yml
Caching for all layers of the Docker image
For every branch
Takes a while to save and load, but will allow us to investigate which are most useful. Will be pruned later
> caching docker images in travis. Fixed #56

- CMakeLists.txt
- cmake/ffig.cmake
> cmake module for ffig

- .gitignore
- .travis.yml
- ffig/FFIG.py
and add .*.swp to .gitignore to prevent git noticing Vim swapfiles.
> Clean up FFIG.py

- ffig/cppmodel.py
> Remove duplicate blank lines in cppmodel.py

- scripts/test-docker.py
I'm lazy and this is useful in tightening the develop-test-commit loop.
> add script for local docker test runs

- .travis.yml
- Dockerfile
> run tests with python 3 on travis

- CMakeLists.txt
- ffig/cppmodel.py
- ffig/templates/_c.cpp.tmpl
- ffig/templates/_c.h.tmpl
- ffig/templates/_cpp.h.tmpl
- ffig/templates/py.tmpl
- input/Tree.h
- scripts/build.py
- tests/test_tree_python_bindings.py
> support void return type in cpp.h c-api and python (#104)

- ffig/FFIG.py
This will help separate biz logic between webapp and local generation.
By splitting it into a named function, we can split another function
that will not write_to_disk but instead feed the module back up to the
client.
Also tried commenting the functions with more detail
> Added write_bindings_to_disk function

- CMakeLists.txt
- Dockerfile
- cmake/ffig.cmake
- ffig/templates/go.tmpl
- tests/go/CMakeLists.txt
- tests/go/test_Shape.go
* Add a template that creates a Go struct with the name of the C++
class.
* Wire it into CMake so we can generate the Go code from the template,
build the test, etc.
* Add a test to make sure Shape is generated as a usable Go struct.
> First steps towards Go bindings.

- CMakeLists.txt
closes #114
fix conditional ruby support
> conditional support for go (#114)

- Dockerfile
Rename dir to ffig
install flask for the app - better install it now before importing code that changes more frequently. 
Will be used for dockerised apps based on ffig
> WIP - Making a general-purpose base image. Fixes #110

- .travis.yml
See how this affects CI build time.
> Remove travis Docker cache

- .appveyor.yml
> use `build_script:` to run build.py

- ffig/FFIG.py
Will need to call this method from rest-api, realised I was passing
wrong args to it
> Corrected method signature and changed comments

- .travis.yml
- CMakeLists.txt
- ffig/templates/_cpp.h.tmpl
- scripts/build.py
- tests/go/CMakeLists.txt
Tests fail - ASAN issues need attention.
> add support for ASAN and run it in docker tests

- doc/Contributing.md
> Add doc for contribution policy and workflow

- ffig/filters/capi_filter.py
See pull request #181 for details.
> Add missing space to match 'const ' instead of 'const'.

- scripts/build.py
> Fix for issue 173 "Clean from VS does not remove generated files"

- CMakeLists.txt
- cmake/ffig.cmake
- ffig/FFIG.py
- ffig/cppmodel.py
- tests/cppmodel/test_classes.py
- tests/cppmodel/test_free_functions.py
Flag is recognized by cmake module and FFIG.py and sets a property that
can be used by templates. No templates make use of the flag (yet).
closes #194
> add flag to force functions to be noexcept

- .gitignore
- demos/PyDataLondon-2017.ipynb
Resurrected and improved demo notebook.
> Pydatalondon 2017 lightning talk

- ffig/filters/capi_filter.py
- ffig/templates/_c.cpp.tmpl
- ffig/templates/_c.h.tmpl
- ffig/templates/_cpp.h.tmpl
- ffig/templates/go.c.tmpl
- ffig/templates/go.tmpl
Improved use of void * typedefs.
Issues with go bindings (at run time).
> N202 capi types and casts

- tests/input/Shape.h
- tests/src/CMakeLists.txt
- tests/src/TestShapeMocks.cpp
> Add missing dependency on Shape_c to fix build race condition

- ffig/include/ffig/attributes.h
- tests/input/Asset.h
- tests/test_asset_bindings.py
- tests/test_type_hints_in_bindings.py
> Add support for named properties

- CMakeLists.txt
- ffig/FFIG.py
- ffig/cppmodel.py
- ffig/generators/__init__.py
- ffig/templates/_c.cpp.tmpl
- ffig/templates/_c.h.tmpl
- ffig/templates/_cpp.h.tmpl
- ffig/templates/_mocks.h.tmpl
- ffig/templates/go.c.tmpl
- ffig/templates/go.tmpl
- ffig/templates/lua.tmpl
- ffig/templates/py2.tmpl
- ffig/templates/py3.tmpl
- ffig/templates/rb.tmpl
- tests/input/Animal.h
- tests/test_animal_bindings.py
remove APIClass class in FFIG implementation
> Add support for multiple classes in a TU

- .travis.yml
> try and fix travis CI for macOS

- .travis.yml
- ffig/filters/capi_filter.py
- requirements.txt
- scripts/codechecks.py
> use autopep8 to get rid of pep8 warning

- docs/ISSUE_TEMPLATE/bug
- docs/ISSUE_TEMPLATE/feature
Add templates for bug reports and feature requests.
> N332: Add issue templates.

- .gitmodules
- CMakeLists.txt
> Use Catch v2

- CMakeLists.txt
I think this improves things. I'm happy to be wrong though.
> Readability improvements for top-level CMakeLists file

- .travis.yml
Run `brew postinstall python` in an attempt to fix the homebrew issue
detailed in [1].
Closes #350.
[1] https://github.com/Homebrew/homebrew-core/issues/24702.
> N350: Fix Travis macOS build.

- .travis.yml
- CMakeLists.txt
- cmake/ffig.cmake
- ffig/FFIG.py
- ffig/cppmodel.py
- tests/cppmodel/test_classes.py
- tests/cppmodel/test_free_functions.py
- tests/input/Tree.h
Remove force-noexcept argument to FFIG.py
> Detect noexcept status from libclang

- ffig/templates/py3.tmpl
Partial support for #264 
Constructors need doing too. I'm dividing this up to make minimal-sized PRs.
> Add noexcept support for Python 3

- ffig/templates/cs.tmpl
- tests/expected_output/Shape.cs.expected
- tests/expected_output/Tree.cs.expected
> Add dotnet noexcept support

- ffig/templates/rb.tmpl
Adds noexcept support to Ruby template
closes #265 
Enhance the Ruby templates and tests to handle function arguments correctly.
> Add noexcept support to Ruby template

- scripts/build.py
- scripts/test-docker.py
Adds support for disabling auto detection of languages
Adds a —local flag so I can test LinuxCI out on the train.
> Dev jbcoe bindings simplifications 

- .appveyor.yml
- .travis.yml
Add --require_X for languages we need CI to discover
> Add --require_X for languages we need CI to discover

- CMakeLists.txt
- tests/go/CMakeLists.txt
Name all tests as test_<LANGUAGE>_<CLASS>
Test file names could be similarly tidied up.
> Name tests as test_LANGUAGE_CLASS

- ffig/FFIG.py
Minor clean up of code layout and formatting.
> Fix FFIG.py formatting

- requirements.txt
Add the cython package to the ffig python requirements.
Sort the requirements.txt package list alphabetically (lexicographically, I guess).
> N449: Add `cython` to requirements.txt and sort package list.

- ffig/templates/_c.h.tmpl
- scripts/build.py
Update build.py to work with any version of Visual Studio
> Get build working on Windows 10 with VS2017

- Dockerfile
Uses LABEL in place of deprecated MAINTAINER
> Use LABEL in place of deprecated MAINTAINER

- BUILD
- ffig.bzl
Add bazel support for other languages.
* Run bazel from scripts/build.py. 
* Install bazel on travis CI. 
* Use starlark (skylark) rules for bazel rather than macros.
https://docs.bazel.build/versions/master/skylark/language.html
> Dev jbcoe bzl cleanup

- .appveyor.yml
- .travis.yml
- scripts/build.py
Modify scripts/build.py to run bazel build :all
Add command line argument to disable bazel build.
> run bazel build :all from scripts/build.py

- Dockerfile
Experiment: Modify Dockerfile to use latest ffig-base image
> Modify Dockerfile to use latest ffig-base image
