_build.sh
generate.py
run_tests.sh
tests/test_asset_bindings.py
tests/test_shape_python_bindings.py
tests/test_tree_python_bindings.py

Various changes to permit the generation to work more easily on a regular OS X system (i.e. one with Xcode, and the various necessary Python packages, but not necessarily with a custom clang build).
- Use clang++ if clang++-3.8 cannot be found.
- Avoid various (DY)LD_LIBRARY_PATH issues when System Integrity Protection (SIP) is enabled.
- Avoid uninitialised variable usage in run_tests.sh causing script termination.

OS X fixes

---

tests/common.py
tests/test_asset_bindings.py
tests/test_shape_python_bindings.py
tests/test_tree_python_bindings.py

Each Python test file contained duplicate code for detecting the OS X
platform and setting the dynamic library load path to include ../output.
This code has been moved into common.py as a function
set_library_path(config, platforms, path) where both platforms and path
have defaults.
The test files have been modified to use this function rather than
replicating code.

Refactor setting of dynamic library path in test files.

---

templates/rb.tmpl

ffi_lib can be an array of paths, instead of a single string. These are
tried in order, so use the existing string as the first one, and specify
two absolute paths in terms of the directory containing the Ruby script
- one for Linux (.so suffix)
- one for OS X (.dylib suffix).
This fixes issue #39.

Give Ruby ffi multiple paths to find the dynamic library.

---

.appveyor.yml
README.md

https://www.appveyor.com will give us free Windows CI.
Issues with the python build script resolved by using CMake/CTest directly.
Needs Python 3.6 due to hang in libclang/ctypes. Only LLVM-64 bit is installed on appveyor.

Add .appveyor.yml for windows CI (#98)

---

tests/cppmodel/util.py

As we do in FFIG.py, set the path to the libclang.dylib library if we're
running on OS X.

Set libclang.dylib path on OS X in cppmodel tests.

---

scripts/build.py

Running the script as ./scripts/build.py worked, but running it as
scripts/build.py did not.
This commit ensures an absolute path is detected by calling
os.path.realpath().

Make build script robust against invocation style.

---

cmake/ffig.cmake

The `RUBY` part should say `PYTHON`.

Fix comment in ffig.cmake

---

ffig/FFIG.py

It is set on line 25 when the module is initialised. main doesn't need
to do it again.

Don't set ffig_dir twice.

---

ffig/FFIG.py
ffig/generators/__init__.py
ffig/generators/go.py
ffig/generators/python/__init__.py
ffig/generators/python/python2.py
ffig/generators/python/python3.py

I'm sure I remember it being easier to get dynamic module imports to work. Last time I wanted to do a plugin arch. in Python it was fairly easy to import based on a filename. Oh well.
This moves the binding generation out of FFIG.py and into the generators sub-package. There's a default function (the existing impl. moved out of FFIG.py), and examples of a module-based generator (go.py) and a package-based generator (python/...). Both just forward their calls to the default generator, right now.

Generators

---

ffig/generators/__init__.py

We're not using it. `__import__` worked better.

Don't import importlib

---

cmake/ffig.cmake
ffig/FFIG.py
ffig/generators/__init__.py
ffig/generators/go.py

* The Go generator writes its output to src/${module}/${module}.go
inside the output directory.
* The CMake file for ffig no longer special-cases Go generation, because
the Go generator takes care of putting files in the right place.
* Logging has been set up throughout FFIG. ffig/FFIG.py sets up basic
logging and defaults the log level to WARNING. Currently, only the
generators package makes use of logging, but this allows us to use it
more widely and keep the configuration consistent across the board.
* The default generator has been refactored to move the generation of
the bindings string outside of the context in which the output file is
opened. This reduces the scope in which the file is open, and fits
better with a model where the generation and the production of files
on disk may …

Produce a Go package from the Go generator.

---

ffig/filters/capi_filter.py
ffig/templates/_c.cpp.tmpl

There's no need to reinterpet_cast to/from a void*.
Closes #138.

N138: Use static_cast instead of reinterpet_cast.

---

ffig/FFIG.py
tests/cppmodel/util.py

If only Xcode Command Line Tools are installed, they seem to go into a different place than when the full Xcode is installed.

Support multiple paths for Xcode Command Line Tools.

---

ffig/FFIG.py

Discovered by running the `vulture` static analysis tool over the FFIG
codebase. There are others listed, but several of those are false
positives which are actually used in the templates.

Remove unused function `get_class_name`.

---

ffig/filters/capi_filter.py
ffig/templates/go.tmpl
tests/go/Shape_test.go

Member functions of C++ types are now methods of Go types. Two additional filters have been added to facilitate this:
go_object(val, type):
returns val.ptr for class types, or val for everything else. This is
analogous to the c_object filter for the C++ bindings.
to_go_method_name(m):
Returns the method name with the first character converted to
uppercase, so that it is available as an exported method of the Go
type.

N146: Use methods in Go bindings.

---

scripts/build.py

Test whether the 'ninja' command is available, and fall back on the
CMake default (i.e. 'make') if 'ninja' is not present.
Ninja is beneficial as it reduces the build time by approximately a
factor 2. However, we shouldn't rely on its presence.

Fall back on 'make' if 'ninja' isn't available.

---

cmake/ffig.cmake
ffig/FFIG.py
ffig/__main__.py

Changes to allow ffig module to be run as `python ffig`.
I can't get `python -m ffig` to work as it has issues with imports. Any input here would be great.

Run ffig module directly

---

ffig/FFIG.py
ffig/annotations.py
ffig/cppmodel.py

The (ffig-specific) annotations code has been moved out of cppmodel.py
and into annotations.py. This makes cppmodel more general (and
reusable).
Closes #253.

N253: Move annotations code out of cppmodel.

---

ffig/templates/py2.tmpl
ffig/templates/py3.tmpl

define `from_param` as a class method like the ctypes decumentation requires.
define `from_c_api` to convert pointers to Python objects.

minor simplifications to python templates

---

ffig/filters/capi_filter.py
ffig/templates/ffig.macros
ffig/templates/go.macros
ffig/templates/go.tmpl

This commit causes the Go bindings to be generated with one type per
derived C++ class (and no type for the base class).
Each generated type has its own set of methods. Each generated type
stores a pointer to the underlying C++ object (which is held as a
pointer to base).
There's currently no support for anything polymorphic, since the base
class is not exposed directly in Go after this commit, and there's no
support for further descendants either.
This allows you to write things like
var c, Circle
c = Shape.Circle_create(...)
and opens up the possibility for smarter handling of objects by exposing
their real type directly to Go.
Closes #147.

N147: Derived classes in Go.

---

CMakeLists.txt

Fixes an issue (absent on Docker) where the shared library can't be found.

Add library path to Lua test

---

CMakeLists.txt
cmake/ffig.cmake
ffig/templates/swift.tmpl
tests/expected_output/Tree.swift.expected

run dotnet text output tests even if dotnet-core is not found

Add rudimentary text tests for swift bindings

---

.travis.yml

The dotnet core runtime requires at least 10.12 to run but the current
setting is xcode8 / macOS 10.11.

Use xcode9.2 / macOS 10.12 images on TravisCI

---

ffig/templates/_cpp.h.tmpl
tests/src/TestCppTree.cpp

Update the C++ template to generate calls to the `_noexcept` C API
functions when an exposed function is marked `noexcept`.
Add tests to verify that the Tree member functions are noexcept in the
bindings. At the moment, we generate the Tree bindings with the
`NOEXCEPT` flag, which forces exported functions to be `noexcept(true)`.
Ultimately, we'll use libclang to determine whether the function is
`noexcept`.
Closes #258.

N258: Support for noexcept member functions in C++ bindings.

---

CMakeLists.txt
cmake/ffig.cmake

Expose a variable `FFIG_SOURCE` from cmake/ffig.cmake so that we can make FFIG build targets depend on the FFIG source and templates.
This adds correct dependencies and avoids having to remember to run `./scripts/build.py --clean` after templates have changed.

Regenerate bindings if any ffig source or templates have changed

---

ffig/templates/cs.tmpl
tests/dotnet/TestShape.cs.in
tests/expected_output/Shape.cs.expected

When a method is annotated as a property, CS code will be generated as follows:
```
public type name {
get {
// C-API call code
}
}
```

Modify dotnet templates to respect properties

---

ffig/filters/capi_filter.py
ffig/templates/_c.cpp.tmpl
ffig/templates/_c.h.tmpl
tests/input/Tree.h

Fix for a loss-of-const bug in Tree bindings (identified by the checked casts).
closes #202

Use checked casts to and from CAPI types

---

README.md

The CI status should be visible as early as possible in the README.

Move the CI status to the top of the README.

---

ffig/clang/cindex.py

This version is taken from clang 6 and includes the support for `ExceptionSpecificationKind` (noexcept detection).

N360 update clang cindex

---

.appveyor.yml

We’re getting spurious test failures on Appveyor Linux - disable ASAN until they can be replicated and fixed.

Disable ASAN on Appveyor Linux

---

.appveyor.yml

This causes the Appveyor build to take longer than the Travis build, and
tests the same thing as the Travis Linux build. There's no point having
this add further delays to getting build status.
Closes #382.

N382: Remove Appveyor Linux build.

---

ffig/templates/py2.tmpl

Identical approach taken as that for Python 3 template.
Drive-by format fixes to Python 2 template made as diff between py3.tmpl and py2.tmpl was open.
closes #256

Add noexcept support for Python 2

---

README.md

noexcept status report requires a newer clang.

Update clang/llvm versions in docs

---

ffig/annotations.py
ffig/templates/_mocks.h.tmpl
ffig/templates/cs.tmpl
ffig/templates/py3.tmpl
tests/expected_output/Shape.cs.expected
tests/input/Shape.h
tests/src/TestShapeMocks.cpp

This pull request adds support for `noexcept` member functions to the C++ mocks template. It also tags the member functions of the `Shape` class hierarchy as `noexcept`, allowing us to test that the mock classes are generated with appropriate `noexcept` specs.
I had to remove a test that throws when no expected value is set for the mock object, as this would violate the `noexcept` specification and cause the test to terminate.
Closes #260.
Begin by determining whether we are happy with the removal of the test for the unset mock objects. From there, inspect the template and `Shape.h` to verify correct implementation.
It occurred to me that we could return some proxy object that has implicit conversion to the correct return type, which would throw if the expected value was not set. I didn't …

N260: noexcept support for C++ mock templates

---

ffig/templates/go.c.tmpl

Initialise CGo static function pointers to NULL.
These are used to store the result of `dlsym` calls during CGo
initialisation. We should initialise the pointers to `NULL` for safety
reasons.
Closes #393

N393: Initialise CGo static function pointers to NULL.

---

ffig/generators/python.py

Fix list of output files from Python generator.
These have not been updated since we modified the way Py2/Py3 generation
was handled.

N395: Fix list of output files from Python generator.

---

CMakeLists.txt
ffig/FFIG.py
tests/ffig/test_build_model.py

As well as building a `cppmodel` from a file, we should be able to build
it from a string containing source code.
This facilitates the ffig-explorer use case, as well as other future
uses.

N397: Support building `cppmodel` objects from source strings.

---

tests/cppmodel/test_model.py

Remove unused `TypeKind` import from `tests/cppmodel/test_model.py`.

N399: Remove unused `TypeKind` import.

---

ffig/templates/go.c.tmpl

This commit modifies the Go templates to support calling functions
marked as `noexcept` via their `_noexcept` C API wrappers.

N261: Support for noexcept functions in Go bindings.

---

ffig/generators/__init__.py
ffig/generators/generator_aliases.py
ffig/generators/go.py
ffig/generators/python.py
tests/ffig/test_generator_list.py

Generators now include a description for each binding they register.
These can be used to add a `--list-generators` feature.
This commit contains work for issue #402 but does not complete the work for this issue.

N402: Add descriptions to binding generators.

---

tests/dotnet/TestNumber.cs
tests/dotnet/TestShape.cs
tests/dotnet/TestTree.cs
tests/dotnet/ffig.net.csproj.in

Changes dotnet tests to use NUnit rather than MSTest
This is related to #349. Perhaps the lower-level commands from mono will give us a faster build?

Use nunit for dotnet tests so that we can support mono easily

---

CMakeLists.txt
cmake/utils.cmake

Moves cmake functions into a utils.cmake file.
This is general cleanup and could be upstreamed to CMake.

Dev jbcoe cmake utils

---

CMakeLists.txt
cmake/ffig.cmake
ffig/FFIG.py

Moves (most)  FFIG-specific build logic into cmake/ffig.cmake
* Clean up the last of the build logic.
* Add targets for each FFIG binding `add_ffig_ruby_library` etc.

Move (most) FFIG-specific build logic into cmake/ffig.cmake

---

.appveyor.yml
.travis.yml
CMakeLists.txt
cmake/ffig.cmake
ffig/generators/dotnet.py
ffig/generators/generator_aliases.py
ffig/templates/csproj.tmpl

Add generator for dotnet bindings. Generator creates project file for
generated source in {module}.net directory. ffig.cmake now adds targets
for generated dotnet assemblies.
closes #438

Add dotnet generator

---

.travis.yml

Disable Julia tests on travis CI while we get the install fixed.
Install Julia on the Docker base image and reactivate (passing) tests.

Disable Julia on travis CI as Julia install is no longer working

---

ffig/FFIG.py
ffig/cppmodel.py
tests/cppmodel/test_classes.py
tests/cppmodel/test_model.py

Causes cppmodel to fail if the parsed file contains errors.
#453 
More work is needed to fail for compile errors in transitively included headers. (Causes test failures on macOS) #458

Add test for compile errors in parsed source file.

---

cmake/ffig.cmake
ffig/FFIG.py
tests/ffig/test_build_model.py

Changes the FFIG.py CLI to require compiler options to locate FFIG headers.
This change is needed for bazel to be able to specify the ffig header include path.
Add Bazel support for FFIG

Pass compiler flags to ffig to locate ffig include directory.

---

.gitignore
scripts/build.py
tests/TestShape.rb
tests/julia/TestShape.jl

BUILD is used by Bazel so build will be used for build config on case insensitive systems.

use build_out for default build output

---

CMakeLists.txt
cmake/ffig.cmake
ffig/FFIG.py
ffig/templates/rs.tmpl
tests/expected_output/Tree.rs.expected

Generate a minimal Rust binding consisting of merely the correct class (struct and impl) name, plus methods (fns), in the style of the existing D binding.
Add a test for the minimal Rust binding
Remove trailing whitespace from the two CMake files that were touched
Remove an unused Python variable
Partly addresses #91 
Extend to generate more Rust code that actually functions

N091 generate Rust bindings

---

cmake/ffig.cmake
ffig.bzl
ffig/generators/c.py

Internal refactor - Use a named generator for C-API bindings

Use a named generator for C-API
